stages:
  - build
  - trigger

.build_vagrant_box:
  stage: build
  interruptible: true
  timeout: 20 minutes
  tags:
    - ansible
  resource_group: vagrant-box-builder
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web"

build_archlinux:
  extends: .build_vagrant_box
  script:
    - source ./build_archlinux.sh
    - if [ "$CI_COMMIT_BRANCH" = "main" ]; then ./publish_box.sh; fi

build_fedora:
  extends: .build_vagrant_box
  script:
    - source ./build_fedora.sh
    - if [ "$CI_COMMIT_BRANCH" = "main" ]; then ./publish_box.sh; fi

build_ubuntu:
  extends: .build_vagrant_box
  script:
    - source ./build_ubuntu.sh
    - if [ "$CI_COMMIT_BRANCH" = "main" ]; then ./publish_box.sh; fi

trigger_ansible_nodes_archlinux:
  stage: trigger
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH == "main"
  needs:
    - build_archlinux
  trigger:
    project: cf_homelab/ansible_nodes
    branch: main
    strategy: depend
  variables:
    FETCH_VAGRANT_BOXES: "true"
    BOX: "archlinux"

trigger_ansible_nodes_fedora:
  stage: trigger
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH == "main"
  needs:
    - build_fedora
  trigger:
    project: cf_homelab/ansible_nodes
    branch: main
    strategy: depend
  variables:
    FETCH_VAGRANT_BOXES: "true"
    BOX: "fedora44"

trigger_ansible_nodes_ubuntu:
  stage: trigger
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH == "main"
  needs:
    - build_ubuntu
  trigger:
    project: cf_homelab/ansible_nodes
    branch: main
    strategy: depend
  variables:
    FETCH_VAGRANT_BOXES: "true"
    BOX: "ubuntu26.04"
