stages:
  - build

.build_vagrant_box:
  stage: build
  interruptible: true
  timeout: 30 minutes
  tags:
    - ansible
  resource_group: vagrant-box-builder
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web"

build_archlinux:
  extends: .build_vagrant_box
  script:
    - source ./build_archlinux.sh
    - if [ "$CI_COMMIT_BRANCH" = "main" ]; then ./publish_box.sh; fi

build_fedora:
  extends: .build_vagrant_box
  script:
    - source ./build_fedora.sh
    - if [ "$CI_COMMIT_BRANCH" = "main" ]; then ./publish_box.sh; fi

build_ubuntu:
  extends: .build_vagrant_box
  script:
    - source ./build_ubuntu.sh
    - if [ "$CI_COMMIT_BRANCH" = "main" ]; then ./publish_box.sh; fi